[tools]
"aqua:theseus-rs/postgresql-binaries" = "latest"
rust = { version = "latest", components = "rustfmt,clippy" }
node = "22"

[env]
PGDATA = ".postgres"
DATABASE_URL = "postgres:///ishikari_dev?host={{config_root}}/.postgres"
