-- Ishikari Job Processing Framework
-- Database schema setup for PostgreSQL
-- Generated by ishikari-cli

-- Create schema if not using public schema
{CREATE_SCHEMA}

-- Create ishikari_job_state enum type
CREATE TYPE {SCHEMA}.ishikari_job_state AS ENUM (
    'available',
    'scheduled',
    'executing',
    'retryable',
    'completed',
    'discarded',
    'cancelled'
);

-- Create ishikari_jobs table
CREATE TABLE {SCHEMA}.ishikari_jobs (
    id bigserial PRIMARY KEY,
    state {SCHEMA}.ishikari_job_state NOT NULL DEFAULT 'available'::{SCHEMA}.ishikari_job_state,
    queue text NOT NULL DEFAULT 'default'::text CHECK (char_length(queue) > 0 AND char_length(queue) < 128),
    worker text NOT NULL CHECK (char_length(worker) > 0 AND char_length(worker) < 128),
    args jsonb NOT NULL DEFAULT '{}'::jsonb,
    errors jsonb[] NOT NULL DEFAULT array[]::jsonb[],
    attempt integer NOT NULL DEFAULT 0,
    max_attempts integer NOT NULL DEFAULT 20 CHECK (max_attempts > 0),
    attempted_by text[],
    priority integer NOT NULL DEFAULT 0 CHECK (priority >= 0 AND priority <= 3),
    tags character varying(255)[] DEFAULT array[]::character varying[],
    meta jsonb DEFAULT '{}'::jsonb,
    inserted_at timestamptz NOT NULL DEFAULT now(),
    scheduled_at timestamptz NOT NULL DEFAULT now(),
    attempted_at timestamptz,
    completed_at timestamptz,
    discarded_at timestamptz,
    cancelled_at timestamptz,
    workflow_id bigint,
    CONSTRAINT ishikari_jobs_attempt_range CHECK (attempt >= 0 AND attempt <= max_attempts)
);

-- Add table comment for version tracking
COMMENT ON TABLE {SCHEMA}.ishikari_jobs IS '1';

-- Create performance indexes
CREATE INDEX ishikari_jobs_state_queue_priority_scheduled_at_id_index 
ON {SCHEMA}.ishikari_jobs(state, queue, priority, scheduled_at, id);

CREATE INDEX ishikari_jobs_args_index 
ON {SCHEMA}.ishikari_jobs USING gin (args);

CREATE INDEX ishikari_jobs_meta_index
ON {SCHEMA}.ishikari_jobs USING gin (meta);

CREATE INDEX ishikari_jobs_workflow_id_index
ON {SCHEMA}.ishikari_jobs (workflow_id)
WHERE workflow_id IS NOT NULL;

-- Create notification function
CREATE OR REPLACE FUNCTION {SCHEMA}.ishikari_jobs_notify()
RETURNS trigger AS $$
DECLARE
    channel text;
    notice json;
BEGIN
    IF new.state = 'available' THEN
        channel := 'ishikari_insert';
        notice := json_build_object('queue', new.queue);
        PERFORM pg_notify(channel, notice::text);
    END IF;
    RETURN null;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for job notifications
CREATE TRIGGER ishikari_jobs_notify_trigger
    AFTER INSERT ON {SCHEMA}.ishikari_jobs
    FOR EACH ROW
    EXECUTE FUNCTION {SCHEMA}.ishikari_jobs_notify();